spring:
  profiles:
    active: upper
  banner:
    location: logo-app
  h2:
    console:
      path: /h2
  datasource:
    url: jdbc:h2:file:./db/flashcards
    username: s28201
    password: cards
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update


